spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fitness_social_network?useSSL=false&serverTimezone=UTC
    username: root
    password: Jeshma@2022
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
