spring:
  datasource:
    url: jdbc:mysql://mysql-19372a1a-onemorerep24x7-bee5.c.aivencloud.com:24758/fitness_social?createDatabaseIfNotExist=true
    username: avnadmin
    password: AVNS_rflvDobFJTFAwmgbo8u
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true  # Set to true to see generated SQL queries
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  spring:
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML
      encoding: UTF-8
      cache: false
  mail:
    host: smtp.gmail.com
    username: onemorerep24x7@gmail.com
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    password: ddsziehyitvjrrqk
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
  mailing:
    frontend:
      activation-url: https://fitness-social-service.vercel.app/activate-account
  file:
    uploads:
      photos-output-path: uploads


server:
  port: 8088
